#+Title: Metric Dimension
#+Latex_header: \DeclareMathOperator{\wt}{wt}
* <2023-03-23 Thu> Introduction
Let $G$ denote a finite graph (directed or undirected). If $u,v \in
V(G)$ are two vertices of $G$ define $d(u,v)$ as being the length of
the shortest path from $u$ to $v$, and $+\infty$ if there is no such
path.  A *resolving set* for $G$ is a subset $S \subseteq V(G)$ such
that for each $u \ne v \in V(G)$ there is a $w \in S$ such that
$d(u,w) \ne d(v,w)$.  Clearly resolving sets exist, since $S = V(G)$
is one such.  The minimum cardinality of a resolving set is called the
*metric dimension* of $G$.

We are particularly interested in the metric dimension of the
hypercube $Q_n$ whose vertices are $\mathbb{F}_2^n$, and edges are
$(u,v)$ such that $u + v$ has weight 1.  Thus the distance metric $d$
is the *Hamming distance*.
** Using MAXSAT
One can approach this problem using ILP (integer linear programming)
or MAXSAT (maximum satisfiability).

For each pair $(u,v) \in V(G)$ with $u \ne v$ define the set
$P_{u,v} := \{w \in V(G) : d(v,w) \ne d(u,w)\}$.  We'll call this set the *pair
resolver*.

Clearly a set $S$ is resolving if and only if for each
$u \ne v \in  V(G)$
 we have $S \cap P_{u,v} \ne \emptyset$.  That is, $S$ contains
at least one element of each $P_{u,v}$.  In other terminology, $S$ is
a *hitting set* for the set system $\{P_{u,v} : u \ne v \in V(G) \}$.
** Questions
This brings up a number of practical questions:

1) Given a subset $S$ which is not a resolving set, efficiently
   produce a pair $(u,v)$ such that $d(w,u) = d(w,v)$ for all $w \in
   S$.  Can we do this without explicitly listing all resolving pairs?
2) Note that if $\sigma \in \text{Aut}(G)$ and $S$ is resolving then
   so is $\sigma(S)$.  This is true because $d(u,v) = d(\sigma u,
   \sigma v)$ for all $u,v \in V(G)$.

Possible approach: One only need to characterize the set of pairs
which have the same Hamming weight.

One might be able to do this inductively: Given a subset $S$, split it
into two subsets $S_0$ and $S_1$, distinguished by the first
coordinate, and denote by $\pi: \mathbb{F}_2^n \rightarrow
\mathbb{F}_2^{n-1}$ the projection onto the last $n-1$ coordinates.
A pair $(u,v)$ will be resolved by $S$ if and only if
a) $u_1 = v_1$ and $(\pi(u), \pi(v))$ is distinguished by $\pi(S)$.
b) $u_1 \ne v_1$ and $\pi(u)$ and $\pi(v)$ ...

An auxilliary question: Given a subset $S \subseteq \mathbb{F}_2^n$,
find an element $u \in \mathbb{F}_2^n$, such that $\max_{v \in S}
d(u,v)$ is minimized.  Call such a $u$ a *centroid* for $S$.

Maximum is hard to deal with.  Use the fact that average is a lower
bound to the maximum.  Suppose that $A_{i,j}$ is the $i$-th bit of the
$j$-th word in $S$.  Suppose that $x$ is the unknown centroid.

Form
\begin{displaymath}
\begin{split}
\sum_j \sum_i (x_i - A_{i,j})^2 & = \sum_i \sum_j (x_i + A_{i,j} -
2 x_i A_{i,j}) \\
 & = \sum_{i,j} A_{i,j} + |S| \text{wt}(x) - 2 \sum_i (\sum_j
A_{i,j}) x_i \\
& = \sum_{i,j} A_{i,j} - 2\sum_i (\sum_j (A_{i,j} - 1/2) - x_i).
\end{split}
\end{displaymath}

** Stabilizer by the hyperoctahedral group
The hyperoctahedral group is the group of automorphisms of $Q_n$.
More concretely, each automorphism is a pair $(\sigma, a)$ where
$\sigma \in S_n$, and $a \in \mathbb{F}_2^n$.  This acts as
$x \mapsto y$, where $y_i = x_{\sigma(i)} + a_i$.  What is the
stabilizer of an element?  We must have $x_i + a_i = x_{\sigma(i)}$.
This means that for each $\sigma$ there is a unique $a$ which makes
this true.  So each element has a stabilizer of order $n!$.  This
makes sense since the group is transitive.  What about subsets?
* Extended formulations
Here's the question: can we describe the hitting set problem more
economically?  More specifically can we specify the collection of
resolving sets more compactly with auxilliary variables?

So, to be more precise, Let $\mathcal{F}$ be a CNF formula in the set
of variables $V$.  We can think of it as specify a subset of $2^V$.  A
hitting set of this would be another subset $\mathcal{H}$ such that
for every $S \in \mathcal{F}$ there is a $T \in \mathcal{H}$ such that
$T \cap S \ne \emptyset$. 

* Some Results.

Let $Q^n$ denote the Hypecube, whose vertices are members
of $\mathbb{F}_2^n$ and whose edges connect two vertices whose weigh
differs by 1.   If $x \in \mathbb{F}_2^n$, let $\wt(x)$ denote the
*Hamming weight* of $x$, $\#\{1 \le i \le n: x_i = 1\}$, and $d(x,y)
:= \wt(x \oplus y)$.

Given $u,v \in \mathbb{F}_2^n$ let $R_{u,v} := \{ x \in
\mathbb{F}_2^n : d(x,u) \ne d(x,v) \}$.

Proposition: We have $R_{u,v} = u \oplus R_{0, u \oplus v}$.

Proposition: We have $R_{0,u} = \{ x \in \mathbb{F}_2^n:  2 \wt(u
\wedge x) \ne \wt(u)\}$. In particular, it includes all elements of
$\mathbb{F}_2^n$ if $u$ has odd weight.

Proof: Note that $\sum_{i=1}^n (-1)^{x_i} = \sum_{i=1}^n (1 - 2 * x_i)
= n - 2 \wt(x)$.  We have
$\wt(u \oplus x)  - \wt(x) = \sum_{i=1}^n ((u_i \oplus x_i) - x_i) =
$\sum_{i, u_i=1} (1- 2 * x_i) = \wt(u) - 2 \wt(u \wedge x)$.  So if $\wt(u)$ is
odd, this is always non-zero.

The equations to detect $(u,v)$ are similar (but not the same) as the
original ones:

* Bases
If $G$ is a permutation group, acting on a finite set $\Omega$, then a
*base* for $G$ is a subset $S \subseteq \Omega$ such that the subgroup
$\{ g \in G: g x = x, \forall x \in S\}$ is trivial. If $x_1, \dots,
x_m \in \Omega$ denote by $G_{x_1, \dots, x_m}$ the pointwise
stabilizer of all the $x_i$.  That is $G_{x_1, \dots, x_m} = \{g \in
G: g x_i = x_i, \forall 1 \le i \le m \}$.  The symmetry breaking
constaints can be of the following form:

Once we have chosen $x_1, \dots, x_m$, choose $x_{m+1}$ being members
of a set of representatives of distinct orbits of $\Omega$ under
$G_{x_1, \dots, x_m}$.  Call that set $S_{x_1, \dots, x_m}$.  The
clauses reprsenting this will be
$(x_1 \wedge \dots \wedge x_m \Rightarrow x)$ for all $x \in S_{x_1,
\dots, x_m}$.

Define: Let $G$ be a finite graph.  If $x,y \in V(G)$ the *resolving
set* of $(x,y)$, $R_{x,y} = \{ z \in V(G) : d(z,x) \ne d(z,y)\}$ is
the set of vertices which are at distinct distances from $x$ and $y$.

Define: An equivalence relation on the vertex set $V(G)$.  Say that
$x \sim y$ if, for all $z,w \in V(G)$ we have $d(x,z) = d(x,w)$ if and
only if $d(y,z) = d(y,w)$.  It is now clear that every resolving set
consists of a union of equivalence classes under this relation.
 
It is clear that if $\sigma$ is an automorphism of
$X$ then it is also a metric automorphism (i.e. $\sigma$ preserves
adjacency), but that might be other metric automorphisms.  A
particular example of a metric automorphism which is not a graph
automorphism occurs with the hypercube $Q^n$.  If $e$ is the all 1's
vector then $d(e \oplus x, y) = n - d(x,y)$. So the metric
automorphism group of $Q^n$ has order $2^{2n} n!$




